### ISSUE TITLE
Use tag groups for better tag granularity and have skip use tags instead of stairs

### ISSUE THREAD

**Issue by ksindi** [ksindi/buildpipe#31]
```
stairs:
  - name: test
    scope: project
    tags:
        - [foo, baz]
        - [bar, baz]
    buildkite:
      command:
        - make test
```
